LearnPAd/learnpad

.components
.gitmodules

Add the simulator as a submodule in lp-simulation-environment

Add simulation platform component

---

lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/core/impl/me/XwikiBridgeInterface.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/core/impl/me/XwikiBridgeInterfaceRestResource.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/core/impl/me/XwikiController.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/core/impl/me/XwikiCoreFacade.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/core/impl/me/XwikiCoreFacadeRestResource.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/me/BridgeInterface.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/me/CoreFacade.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/me/rest/CheckModelSet.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/me/rest/ImportModelSet.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/me/rest/RetrieveFeedbacks.java

Come from the branhc on Gulyx repo.

Add Modelling Environment API

---

lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/BridgeInterface.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/CoreFacade.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/AddExecutionState.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/AskRecommendation.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/GetComments.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/GetSimilarCases.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/ListExecutionStates.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/ModelSetImported.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/ResourceNotification.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/SimulationNotification.java

This is the same PR done on Gulyx repo but it's better to to them on the official repo (it also triggered Travis).

API for Ontology Recommendation

---

lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/core/impl/cw/XwikiBridgeInterface.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/core/impl/cw/XwikiBridgeInterfaceRestResource.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/core/impl/cw/XwikiController.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/core/impl/cw/XwikiCoreFacade.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/core/impl/cw/XwikiCoreFacadeRestResource.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/Bridge.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/BridgeInterface.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/CoreFacade.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/CommentNotification.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/ContentVerified.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/GetComments.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/GetResource.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/ModelSetImported.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/ModelVerified.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/ResourceNotification.java

This is the same PR done on Gulyx repo but it's better to to them on the official repo (it also triggered Travis).

APIs for the Collaborative Workspace

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-transformer/pom.xml
lp-core-platform/lp-cp-metamodel/pom.xml
lp-core-platform/pom.xml

Creation of the Maven submodules in order for Francesco to work on EMF integration into the Learn PAd platform.

Emf submodules

---

lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/ColloborativeContentVerifications.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/StaticContentVerifications.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/Annotation.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/Content.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/Node.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/collaborative/AnnotatedCollaborativeContentAnalysis.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/collaborative/CollaborativeContent.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/stat/AnnotatedStaticContentAnalysis.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/stat/StaticContent.java

*fix bug on set content
*constructor added for same data classes
*renamed annotateCollaborativeAnalysis class into
annotatedCollaborativeAnalysis
**renamed annotateStaticAnalysis class into annotatedStaticAnalysis

fix bug, constructor added and renamed classes

---

lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/ColloborativeContentVerifications.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/StaticContentVerifications.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/Content.java

Delete wrong annotations of the POST request

Delete wrong annotations

---

README.md
build-system/launch.sh
launch

This is a general start/stop script for the whole platform.  It will consider all the component at once.

[all] Create a launch system

---

lp-simulation-environment/pom.xml

Several pom.xml improvements that should increase compatibility with various platforms and build tools.

[sim] improve pom

---

lp-simulation-environment/pom.xml
lp-simulation-environment/src/main/java/eu/learnpad/simulator/IRobotHandler.java
lp-simulation-environment/src/main/java/eu/learnpad/simulator/Simulator.java
lp-simulation-environment/src/main/java/eu/learnpad/simulator/processmanager/AbstractProcessDispatcher.java
lp-simulation-environment/src/main/java/eu/learnpad/simulator/robot/IRobot.java
lp-simulation-environment/src/main/java/eu/learnpad/simulator/robot/IRobotFactory.java
lp-simulation-environment/src/main/java/eu/learnpad/simulator/robot/IRobotInputExtractor.java
lp-simulation-environment/src/main/java/eu/learnpad/simulator/robot/RobotUserEventReceiverWrapper.java
lp-simulation-environment/src/main/java/eu/learnpad/simulator/robot/activiti/ActivitiRobotInputExtractor.java
lp-simulation-environment/src/main/java/eu/learnpad/simulator/robot/activiti/markovrobot/MarkovBot.java
lp-simulation-environment/src/main/java/eu/learnpad/simulator/robot/activiti/markovrobot/MarkovBotFactory.java
lp-simulation-environment/src/main/java/eu/learnpad/simulator/robot/activiti/markovrobot/MarkovData.java
lp-simulation-environment/src/main/java/eu/learnpad/simulator/robot/activiti/simplerobot/SimpleRobot.java
lp-simulation-environment/src/main/java/eu/learnpad/simulator/robot/activiti/simplerobot/SimpleRobotFactory.java
lp-simulation-environment/src/main/java/eu/learnpad/simulator/uihandler/formhandler/AbstractFormHandler.java
lp-simulation-environment/src/main/java/eu/learnpad/simulator/uihandler/formhandler/activiti2jsonform/ActivitiToJsonFormFormHandler.java
lp-simulation-environment/src/main/java/eu/learnpad/simulator/uihandler/formhandler/dataobject2jsonform/DataObjectToJsonFormFormHandler.java
lp-simulation-environment/src/main/java/eu/learnpad/simulator/utils/SimpleMarkovModel.java
lp-simulation-environment/src/main/resources/static/HeightMonitor.js
lp-simulation-environment/src/main/resources/static/Task.js
lp-simulation-environment/src/main/resources/static/TaskReceiver.js
lp-simulation-environment/src/main/resources/ui-process.html
lp-simulation-environment/src/main/resources/ui-singleprocess.html
lp-simulation-environment/src/main/resources/ui.html

This PR adds two functionalities that had been "sleeping" in some branchs for too long:
- Improving form generation with optional data object enriched format and elements
- adding robots

[sim] putting main repo up to date with lastest sim developpements

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPCode/BaseElementDisplayBPMNMacro.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPCode/FeedbackButtonMacro.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPCode/OrganizationMacro.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPCode/WeavingMacro.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPUI/ModelSheet.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPUI/SimulationEnvironment.xml

* Improvement of simulation environment
* Move the workflow buttons
* Improve Organization macro
* Add buttons for simulation and browsing mode in a model

[cw] Improve UI

---

lp-simulation-environment/build
lp-simulation-environment/scripts/start
lp-simulation-environment/scripts/stop
lp-simulation-environment/simulator/src/main/resources/static/HeightMonitor.js

- correct errors in build script
- remove debug logs

[sim] build corrections and cleaning

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/api/impl/SimulatorBridgeImpl.java
lp-simulation-environment/simulator/src/main/resources/static/HeightMonitor.js
lp-simulation-environment/simulator/src/main/resources/static/Task.js
lp-simulation-environment/simulator/src/main/resources/static/TaskReceiver.js
lp-simulation-environment/simulator/src/main/resources/ui-process.html
lp-simulation-environment/simulator/src/main/resources/ui-singleprocess.html
lp-simulation-environment/simulator/src/main/resources/ui.html

This PR makes some corrections and improvements for the integration with the CP:
- minor bugs correction
- interface height monitoring accuracy improvements
- interface changes when in "integrated" mode for nicer integration with CW UI
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/160)

[sim] improve integration with core platform

---

.gitignore
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/UICWBridge.java
lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPUI/SimulationEnvironment.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-service/src/main/java/eu/learnpad/cw/service/script/LearnpadScriptService.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/data/UserData.java

* Improve the call of the `addProcessInstance`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/161)

[cw] Simulation integration

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java
lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPUI/ModelSheet.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPUI/SimulationEnvironment.xml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/162)

[cw] Simulation integration for IDs

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPUI/RecommendationPanel.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-service/src/main/java/eu/learnpad/cw/service/script/LearnpadScriptService.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/or/XwikiBridgeInterfaceRestResource.java
lp-ontology-recommender/src/main/java/eu/learnpad/ontology/recommender/Inferencer.java
lp-ontology-recommender/src/main/resources/application.properties
lp-ontology-recommender/src/test/java/eu/learnpad/ontology/AbstractUnitTest.java
lp-ontology-recommender/src/test/resources/application.properties
lp-ontology-recommender/src/test/resources/ontology/instances/modelset-titolo-unico-v5/1/modelset-titolo-unico-v5.ttl

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/165)

[cw/or] Improve integration of the recommender

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/Main.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImpl.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/WebServer.java
lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/uihandler/webserver/WebServerTest.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/166)

[sim] Fix a problem about getting the IP

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/Main.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/api/impl/SimulatorBridgeImpl.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImpl.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/WebServer.java
lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/uihandler/webserver/WebServerTest.java

This is the continuation of PR #166 started by @woshilapin.
Previous PR was fixing two problems:
- Simulator using the wrong IP address
- Servlet error due to users being added twice
However, it caused the travis build to fail by being too strict in IP selection (and did not fix up the user problem completely).
This PR tries to address these last problems.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/168)

  [sim] Fix a problem about getting the IP (followup)

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-transformer/src/main/java/eu/learnpad/transformations/launchers/ATLTransformationLauncher.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-transformer/src/main/java/eu/learnpad/transformations/launchers/AcceleoTransformationLauncher.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-transformer/src/main/java/eu/learnpad/transformations/launchers/AlignmentLauncher.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-transformer/src/main/java/eu/learnpad/transformations/launchers/ChainLauncher.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-transformer/src/main/java/eu/learnpad/transformations/model2model/ATLTransformation.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-transformer/src/main/java/eu/learnpad/transformations/model2text/generator/AcceleoStandaloneStarter.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-transformer/src/main/java/eu/learnpad/transformations/preprocessing/Alignment.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-transformer/src/main/java/eu/learnpad/transformations/preprocessing/MyComparator.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-transformer/src/main/java/eu/learnpad/transformations/preprocessing/Utils.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/169)

[cw] Insertion of comments for JavaDoc and general refactoring

---

lp-simulation-environment/simulator/src/main/resources/dataobjects/TitoloUnico_init
lp-simulation-environment/simulator/src/main/resources/validation_db.json

Add validation for more SUAP test cases.
Add test cases to SUAP available cases selection.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/170)

[sim] add more test cases to SUAP demo process

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/datastructures/LearnPadTaskSubmissionResult.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/AbstractProcessDispatcher.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/TaskServlet.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/task/send/Validated.java
lp-simulation-environment/simulator/src/main/resources/static/Task.js

The Simulator now displays the score of each task along with the session score
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/172)

[sim] Simulator UI now display task scores

---

launch

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/176)

Modifications launch script

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPUI/ModelSetSheet.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPUI/ModelSheet.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPUI/WebHome.xml
lp-platform/lp-platform-distributions/lp-platform-ui/pom.xml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/175)

[cw] Tiny updates of the UI

---

launch

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/178)

changed the string of the usage message in launch

---

lp-simulation-environment/simulator/pom.xml
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/Main.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/AbstractProcessDispatcher.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManager.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/processdispatcher/ActivitiProcessDispatcher.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/workarounds/msg/BPMNTransformer.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/workarounds/msg/JavaMsgTask.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/workarounds/msg/MessageInfoData.java
lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManagerTest.java
lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/processmanager/activiti/processdispatcher/ActivitiProcessDispatcherTest.java
lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/processmanager/activiti/workaround/smsg/BPMNTransformerTest.java
lp-simulation-environment/simulator/src/test/resources/collaboration_msg_with_events.bpmn20.xml
lp-simulation-environment/simulator/src/test/resources/collaboration_msg_with_tasks.bpmn20.xml

The Activiti engine does not support some BPMN elements used for inter-process communication (some message and signals types). However we will want to support these elements in the project.
This PR introduces some workarounds to support BPMN including these elements.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/180)

[sim] Support for some Activiti workaround

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPUI/RecommendationPanel.xml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/185)

[cw] Integrate Learning Materials in the Recommendation panel

---

lp-platform/build
lp-platform/lp-platform-distributions/lp-platform-ui/pom.xml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/186)

[dev] Add some useful dependencies for dev purpose in XWiki

---

lp-simulation-environment/simulator/pom.xml
lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/api/rest/corefacade/SimRestAPICoreFacadeTest.java
lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/api/rest/corefacade/SimRestAPITestCoreFacadeInterface.java
lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/api/rest/corefacade/SimRestAPITestCoreFacadeServer.java

Add some tests for Core Facade API interaction, mostly about serialization/deserialization of the data (+some dependencies and utility classes for creating the tests).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/189)

[sim] Add some tests for Simulator REST API

---

lp-model-verification/verification-component/src/main/java/eu/learnpad/verification/JAXRSService.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/190)

set class as deprecated

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/IProcessManager.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/datastructures/LearnPadTask.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/event/AbstractSimEvent.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/AbstractProcessDispatcher.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/IProcessDispatcher.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManager.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/processdispatcher/ActivitiProcessDispatcher.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/TaskServlet.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImpl.java
lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/processmanager/activiti/processdispatcher/ActivitiProcessDispatcherTest.java
lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImplTest.java

This PR introduces various bugfixes and improvements in the simulator
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/191)

Various bugfixes and improvements

---

lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/qm/XwikiCoreFacadeRestResource.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/194)

Started the implementation of REST invocations from the QM to the CP

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/IUserHandler.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/api/impl/SimulatorBridgeImpl.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImpl.java
lp-simulation-environment/simulator/src/main/resources/static/Task.js
lp-simulation-environment/simulator/src/main/resources/static/Users.js
lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/MainTest.java
lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImplTest.java

This PR integrates the user profiles in the simulator Web UI.
Previously the user data was hardcoded at the simulator Web UI client level. With this PR the simulator uses the provided user data to display the users information in the UI.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/200)

[sim] User Information integration in UI

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-transformer/src/main/java/eu/learnpad/transformations/model2text/main/generate.emtl
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-transformer/src/main/java/eu/learnpad/transformations/model2text/main/generate.mtl
lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/LPCode/Translations.xml
lp-core-platform/lp-cp-xwiki-implementation/pom.xml
lp-core-platform/pom.xml
lp-platform/lp-platform-distributions/lp-platform-jetty-hsqldb/pom.xml
lp-platform/lp-platform-distributions/lp-platform-ui/pom.xml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/198)

[cp/cw] Upgrade to XWiki 7.4 and dependencies

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-skin/pom.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-skin/src/assemble/skin.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-skin/src/main/resources/learnpad/layoutExtraVars.vm
lp-collaborative-workspace/lp-cw-component/lp-cw-component-skin/src/main/resources/learnpad/skin.properties
lp-collaborative-workspace/lp-cw-component/pom.xml
lp-platform/lp-platform-distributions/lp-platform-jetty-hsqldb/pom.xml
lp-platform/lp-platform-distributions/lp-platform-ui/pom.xml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/204)

[cw] Create a Learn PAd skin

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/GetFeedbacks.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/data/Artefact.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/data/Attribute.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/data/PFResults.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/data/Patch.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/data/PatchType.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/data/Patches.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/me/rest/RetrieveFeedbacks.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiBridgeInterfaceRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/me/XwikiController.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/me/XwikiCoreFacadeRestResource.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/207)

[cp] Improve model of feedbacks with patches

---

lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/MainTest.java

Change the value of the port used for the server during tests, as the
previous value conflicted with another component and could cause build
failures during testing.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/210)

[sim] Update server test port

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-transformer/resources/transformation/ado2xwiki.atl

new version of the transformation
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/209)

[CW] Fix and improvement in ATL m2m transformation

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/ChatServlet.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/WebServer.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/userchat/IChatMsg.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/userchat/receive/BaseReceiveMessage.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/userchat/receive/Register.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/userchat/receive/Submit.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/userchat/receive/Subscribe.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/userchat/receive/Unsubscribe.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/userchat/send/ReceiveErrorNotification.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/userchat/send/ReceiveJoinNotification.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/userchat/send/ReceiveLeftNotification.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/userchat/send/ReceiveMsg.java
lp-simulation-environment/simulator/src/main/resources/static/Task.js
lp-simulation-environment/simulator/src/main/resources/static/Webchat.js
lp-simulation-environment/simulator/src/main/resources/ui.html

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/211)

[sim] add simulator session chat system

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-application/src/main/resources/CoreCode/CheckPushModelSet.xml
lp-core-platform/lp-cp-apis/pom.xml
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/me/XwikiController.java
lp-platform/lp-platform-distributions/lp-platform-jetty-hsqldb/pom.xml

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/215)

[cp] Small fixes

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-transformer/src/main/java/eu/learnpad/transformations/launchers/ChainLauncher.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-transformer/src/main/java/eu/learnpad/transformations/launchers/Launcher.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/218)

[cw] Deleted output stream parameter as input of the chain API

---

lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/BridgeInterface.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/CoreFacade.java

Update REST API paths according to new project standard.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/222)

[sim] Update Rest API paths

---

lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/me/XwikiController.java

The interactions with that components are now triggered
by the Controller of the MV.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/221)

Removed unused references to the BridgeInterface of : SIM, QM, QR.

---

lp-model-verification/verification-component-understandability-plugin/src/main/java/eu/learnpad/verification/plugin/bpmn/guideline/factory/GuidelinesFactory.java
lp-model-verification/verification-component-understandability-plugin/src/main/java/eu/learnpad/verification/plugin/bpmn/guideline/impl/ActivityDescription.java
lp-model-verification/verification-component-understandability-plugin/src/main/java/eu/learnpad/verification/plugin/bpmn/guideline/impl/ApplyHierarchicalStructure.java
lp-model-verification/verification-component-understandability-plugin/src/main/java/eu/learnpad/verification/plugin/bpmn/guideline/impl/labeling/LabelingANDGateways.java
lp-model-verification/verification-component-understandability-plugin/src/main/java/eu/learnpad/verification/plugin/bpmn/guideline/impl/labeling/LabelingConvergingGateways.java
lp-model-verification/verification-component-understandability-plugin/src/main/java/eu/learnpad/verification/plugin/interfaces/impl/BPMNUnderstandability.java
lp-model-verification/verification-component-understandability-plugin/src/test/java/eu/learnpad/verification/plugin/bpmn/guideline/factory/GuidelinesFactoryTest.java
lp-model-verification/verification-component-understandability-plugin/src/test/resources/EPBR - Business Process.bpmn
lp-model-verification/verification-component-understandability-plugin/src/test/resources/EPBR-Coordinator/20903.bpmn
lp-model-verification/verification-component-understandability-plugin/src/test/resources/EPBR-Coordinator/21099.bpmn
lp-model-verification/verification-component-understandability-plugin/src/test/resources/EPBR-Coordinator/21203.bpmn
lp-model-verification/verification-component-understandability-plugin/src/test/resources/EPBR-Coordinator/21385.bpmn
lp-model-verification/verification-component-understandability-plugin/src/test/resources/EPBR-Coordinator/21417.bpmn
lp-model-verification/verification-component-understandability-plugin/src/test/resources/EPBR-Coordinator/21447.bpmn
lp-model-verification/verification-component-understandability-plugin/src/test/resources/EPBR-Coordinator/21823.bpmn
lp-model-verification/verification-component-understandability-plugin/src/test/resources/TitoloUnico/20250.bpmn
lp-model-verification/verification-component-understandability-plugin/src/test/resources/TitoloUnico/20386.bpmn
lp-model-verification/verification-component-understandability-plugin/src/test/resources/TitoloUnico/20461.bpmn
lp-model-verification/verification-component-understandability-plugin/src/test/resources/TitoloUnico/diagram.bpmn

- some bug fixed
- ado attribute changed to identify the name of the gateway in LabelingConvergingGateways
- In ME all messages flow aren't linear, this is one problem of the conversion from ado to bpmn file,
for this reason I disabled relative guideline id 46.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/224)

[MV] verification-component-understandability-plugin improved

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/ModelImporter.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/me/rest/ImportModelSet.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/mv/rest/ModelImporter.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/ModelImporter.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiController.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiCoreFacadeRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/me/XwikiController.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/me/XwikiCoreFacadeRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/mv/XwikiController.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/mv/XwikiCoreFacadeRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/or/XwikiController.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/or/XwikiCoreFacadeRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/rest/XWikiRestUtils.java
lp-model-verification/lp-verification-component/src/main/java/eu/learnpad/verificationComponent/BridgeImpl.java
lp-model-verification/lp-verification-component/src/main/java/eu/learnpad/verificationComponent/PlatformFacadeImpl.java
lp-ontology-recommender/src/main/java/eu/learnpad/ontology/transformation/SimpleModelTransformator.java
lp-ontology-recommender/src/main/java/eu/learnpad/or/impl/OntologyRecommenderImpl.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/226)

[cp] Change from byte[] to InputStream in REST

---

lp-core-platform/pom.xml
lp-platform/lp-platform-distributions/lp-platform-ui/pom.xml

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/230)

[cp] Update of versions for XWiki

---

lp-model-transformer/scripts/start

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/231)

[mt] Fix start script

---

lp-model-transformer/src/main/java/eu/learnpad/transformations/launchers/AcceleoTransformationLauncher.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/233)

[mt] Return the path after Acceleo transformation

---

lp-ontology-recommender/src/test/java/eu/learnpad/ontology/transformation/SimpleModelTransformatorTest.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/234)

[or] Fix tests from byte[] to InputStream

---

lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/sim/XwikiBridgeInterfaceRestResource.java
lp-model-transformer/scripts/start

@woshilapin please wait to @tomjorquera review before accepting this PR
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/232)

Cp sim bridge rest resource

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/CoreFacade.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/Transformer.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiController.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiCoreFacadeRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/mt/XwikiBridgeInterfaceRestResource.java
lp-model-transformer/src/main/java/eu/learnpad/mt/rest/BridgeImpl.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/237)

[cw] Run transformations and upload package

---

lp-platform/lp-platform-distributions/lp-platform-jetty-hsqldb/pom.xml
lp-platform/lp-platform-distributions/lp-platform-ui/pom.xml

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/238)

[cw] Add dependencies for EM

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/BridgeInterface.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/NotifyRecommendations.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiBridgeInterfaceRestResource.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/239)

Cw api notifications from or

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/NotifyRecommendations.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiBridgeInterfaceRestResource.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/240)

[cw] Change name of notify API

---

lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/AskRecommendation.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/SimulationNotification.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiController.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/or/XwikiBridgeInterfaceRestResource.java
lp-ontology-recommender/src/main/java/eu/learnpad/or/impl/OntologyRecommenderImpl.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/244)

Fixed wrong path definitions

---

lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/sim/XwikiBridgeInterfaceRestResource.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/249)

Fixed the ObjectWriter instance according to Tom's suggestion

---

lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/probe/GlimpseAbstractProbe.java
lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/probe/GlimpseProbe.java
lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/probe/GlimpseProbeInterface.java

new probe
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/252)

updated Probe for simulator

---

lp-platform/lp-platform-distributions/lp-platform-jetty-hsqldb/pom.xml

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/256)

[cp] Fix the XAR dependencies for Learn PAd

---

lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/data/Experts.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/data/LearningMaterials.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/data/SimilarCases.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/data/States.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/260)

[or] Fix some incomplete instanciations

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/NotifyRecommendations.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/AskRecommendation.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/SimulationNotification.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiBridgeInterfaceRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/or/XwikiBridgeInterfaceRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/sim/XwikiController.java
lp-ontology-recommender/src/main/java/eu/learnpad/or/impl/OntologyRecommenderImpl.java

* eu.learnpad.cw.rest.NotifyRecommendations.notifyRecommendations --> added parameter for userID
* eu.learnpad.or.rest.AskRecommendation.askRecommendation --> extended paramente list in order to include users, modelsetid, artifactid
* eu.learnpad.or.rest.SimulationNotification.simulationTaskEndNotification --> added parameter for simulation session data
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/254)

API update as from our discussion in Rome

---

lp-content-analysis/scripts/start
lp-model-verification/scripts/start
lp-simulation-environment/scripts/start

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/262)

[all] Print logs into files

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/NotifyRecommendations.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiBridgeInterfaceRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/sim/XwikiController.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/263)

[cp] Fix PR #254

---

lp-platform/lp-platform-distributions/lp-platform-jetty-hsqldb/pom.xml

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/266)

[cw] Add Scripting Documentation Application

---

lp-core-platform/pom.xml
lp-platform/lp-platform-distributions/pom.xml

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/269)

[cp] Update XWiki to 7.4.2

---

lp-model-transformer/src/main/java/eu/learnpad/transformations/preprocessing/Alignment.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/270)

[mt] Delete files only if they exists

---

lp-core-platform/lp-cp-xwiki-implementation/pom.xml

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/272)

[cp] Remove slf4j dependencies (already existing)

---

lp-core-platform/lp-cp-apis/pom.xml
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/SimulationNotification.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/data/SimulationData.java
lp-core-platform/lp-cp-apis/src/test/java/eu/learnpad/or/test/OrAPITest.java
lp-core-platform/lp-cp-xwiki-implementation/pom.xml
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/or/XwikiBridgeInterfaceRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/sim/XwikiController.java
lp-ontology-recommender/src/main/java/eu/learnpad/or/impl/OntologyRecommenderImpl.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/275)

Or api fix on the maps parameters

---

lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/sim/XwikiController.java

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/278)

Added the check on a possible null list of involved users

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Render.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/CollaborativeDocumentSheet.xml
lp-platform/lp-platform-distributions/lp-platform-jetty-hsqldb/pom.xml

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/286)

[cw] Get correct plain and HTML content

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/292)

[cw] Put default values for empty fields

---

lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/or/XwikiBridgeInterfaceRestResource.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/293)

[cp] Fix Bridge REST resource for OR

---

lp-platform/lp-platform-distributions/lp-platform-jetty-hsqldb/pom.xml
lp-platform/lp-platform-distributions/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/295)

[cw] Add CKEditor as the WYSIWYG editor

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Render.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/296)

[cw] Improve rendering of plain for headers

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/BaseElementClass.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/CollaborativeDocumentTemplate.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/FeedbackButtonMacro.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/ModelClass.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/BaseElementSheet.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/CollaborativeDocumentSheet.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/FeedbackSheet.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/ModelSetSheet.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/ModelSheet.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationPanel.xml
lp-model-transformer/src/main/resources/transformation/ado2xwiki.atl

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/297)

[mt/cw] Use Nested Spaces to organize pages

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-skin/src/main/resources/learnpad/layoutExtraVars.vm

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/298)

[cw] Fix velocity syntax error in skin

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/CollaborativeDocumentTemplate.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Render.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/299)

[cw] Add punctuation in the plain rendering

---

lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/me/rest/data/ModelSetType.java
lp-model-transformer/src/main/java/eu/learnpad/mt/rest/BridgeImpl.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/300)

Todo on model set type

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/ModelSheet.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/302)

[cw] Display images for every models

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/ModelSheet.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/305)

[cw] Test presence of files in ZIP attachment

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/BaseElementSheet.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/306)

[cw] Fix the collaborate button when document exists

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/CollaborativeDocumentSheet.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/307)

[cw] Fix the Validate sub-requests

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Render.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/308)

[cw] Improve plain rendering for lists

---

lp-simulation-environment/monitoring/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/311)

new classpath on pom.xml

---

lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/ActiveMQRunner.java
lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/MainMonitoring.java
lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/utils/TesterJMSConnection.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/314)

Mon fix on the active mq runner

---

lp-simulation-environment/README.md
lp-simulation-environment/scripts/start

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/315)

Sim modifications on start script

---

lp-platform/lp-platform-distributions/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/317)

[cw] Fix dependency for FontAwesome

---

lp-platform/lp-platform-distributions/lp-platform-jetty-hsqldb/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/320)

[cw] Update version of CKEditor for XWiki

---

lp-platform/lp-platform-distributions/lp-platform-jetty-hsqldb/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/319)

[cw] Fix the $doc.display in CollaborativeDocumentSheet

---

lp-simulation-environment/monitoring/configFiles/startupRule.drl
lp-simulation-environment/monitoring/scripts/configFiles/startupRule.drl
lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/controller/MySqlController.java
lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/impl/ComplexEventProcessorImpl.java
lp-simulation-environment/monitoring/src/test/java/eu/learnpad/simulator/mon/MyGlimpseProbe_SimMonLearnPAd.java

Database disabled
Rule updated according to the events described in eu.learnpad.sim.rest.event.EventType;
( lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/EventType.java )
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/324)

Rule update for CP notification

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-skin/src/main/resources/learnpad/layoutExtraVars.vm

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/323)

[cw] Reintroduce ability to login from UI

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/WebServer.java

Forgot to remove a debug println. Corrected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/325)

[sim] remove debug prints

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/328)

Added logs for received recs in the CW

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationSimPanel.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/329)

Cw sim rec panel

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/LinkButtonsMacro.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/LinkClass.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/WeavingMacro.xml
lp-model-transformer/src/main/resources/transformation/ado2xwiki.atl

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/332)

[mt/cw] Improve structure of Links objects

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/UICWBridge.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/impl/persistence/PairKeyString.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/impl/persistence/RecommendationsStore.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/impl/persistence/RecommendationsStoreMultipleMaps.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/impl/persistence/RecommendationsStoreWithPairs.java
lp-collaborative-workspace/lp-cw-component/lp-cw-component-service/src/main/java/eu/learnpad/cw/service/script/LearnpadScriptService.java
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationPanel.xml
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiBridge.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/333)

CW : Recommendations from Simulation -- first tentative

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationPanel.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationPanelSheet.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/SimulationEnvironment.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/334)

[cw] Introduce Recommendation in Simulation

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationPanel.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/335)

[cw] Display similar cases in recommendation panel

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationPanel.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/336)

[cw] Fix parenthesis in RecommendationPanel tests

---

lp-simulation-environment/simulator/src/main/resources/process/suap.bpmn20.xml

Forgot to add a data object to the Y2 demo process. Add it and update
process with correct name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/337)

[sim] Add missing data object with correct name

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationPanel.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/339)

[cw] Improve UI of similar cases

---

lp-content-analysis/src/main/java/eu/learnpad/ca/analysis/completeness/Completeness.java
lp-content-analysis/src/main/java/eu/learnpad/ca/main/Main.java

bug fix now CA component accept external connection
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/341)

[ca] lp-content-analysis improved 

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationPanel.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/345)

[cw] Introduce recommendations for models and modelset

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationPanel.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/347)

[cw] Add simulation button in recommendation panel

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/349)

[all] Increase memory of JVM for Maven in Travis

---

lp-platform/lp-platform-distributions/lp-platform-jetty-hsqldb/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/343)

[cw] Add user profile page

---

lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/data/ListOfStringWrapper.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/data/SimilarCase.java
lp-core-platform/lp-cp-apis/src/test/java/eu/learnpad/or/test/OrAPITest.java
lp-ontology-recommender/pom.xml
lp-ontology-recommender/src/main/java/eu/learnpad/ontology/recommender/Recommender.java
lp-ontology-recommender/src/main/java/eu/learnpad/ontology/recommender/cbr/CBRAdapter.java
lp-ontology-recommender/src/main/resources/application.properties
lp-ontology-recommender/src/test/java/eu/learnpad/ontology/recommender/RecommenderTest.java
lp-ontology-recommender/src/test/resources/application.properties

... and also added a dependency to the OR pom.
Details are available here : https://github.com/LearnPAd/learnpad/issues/342
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/348)

Or patch for unsupported operation exception in cbr adapter

---

lp-simulation-environment/simulator/src/main/resources/ui-process.html
lp-simulation-environment/simulator/src/main/resources/ui-singleprocess.html
lp-simulation-environment/simulator/src/main/resources/ui.html

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/353)

[sim] Change background color for CW integration

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/SimulationEnvironment.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/355)

[cw] Improve integration with SIM

---

lp-platform/lp-platform-distributions/lp-platform-jetty-hsqldb/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/358)

[cw] Update version of CKEditor

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/SimulationEnvironment.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/357)

Proposed a fix for the title of SimulationEnvironment

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-skin/src/main/resources/learnpad/less/learnpad.less
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/ModelSheet.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/360)

[cw] Add contribute button for models

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-skin/src/main/resources/learnpad/less/learnpad.less
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/CollaborativeDocumentSheet.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/361)

[cw] Add 'edit' button for Collaborative Document

---

lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/sim/XwikiController.java

fix in the CP in order to deal with Recs by user's email
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/363)

IDs Alligment in CP

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/WebHome.xml
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/sim/XwikiController.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/364)

[cw] Improve Jumbotron for better translations

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/WebHome.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/365)

[cw] Change title for landing page

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationPanel.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/366)

[cw] Do not display panel block if empty

---

lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/mv/XwikiController.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/367)

[cp] Enable blocking import when verification failed

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationPanel.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/368)

[cw] Fix compilation problems in the Recommendation panel

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/activiti/ProbeEventReceiver.java
lp-simulation-environment/simulator/src/main/resources/static/Process.js
lp-simulation-environment/simulator/src/main/resources/static/SingleProcess.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/370)

[sim] Various fixes for Y2 demo

---

lp-ontology-recommender/src/test/java/eu/learnpad/ontology/recommender/RecommenderTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/372)

Tests for the Recommender improved

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/373)

[cw] Remove dummy patches

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/374)

[cw] Fix the request to get feedbacks

---

lp-simulation-environment/simulator/src/main/resources/process/suap.bpmn20.xml

Y2 demo process has been updated to the new version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/377)

[sim] Update Y2 demo process to latest changes

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/FeedbackButtonMacro.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/378)

[cw] Fix the IDs in feedbacks

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/ModelSetSheet.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/ModelSheet.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/379)

[cw] Add 'contribute' button to modelset

---

lp-simulation-environment/simulator/src/main/resources/process/suap.bpmn20.xml

Add BPMNDI to Y2 demo process in order to display automatically
generated process diagram progression.
NOTE: This does not modify the process itself. It is only a "cosmetic"
modification.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/384)

[sim] Add BPMNDI info to Y2 demo process

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/SimulationEnvironment.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/386)

[cw] Fix the background color of Recommendation Panel in Simulation

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/SimulationEnvironment.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/387)

[cw] Make the Recommendation Panel stick on top-right during Simulation

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-skin/src/main/resources/learnpad/less/learnpad.less
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationPanel.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/SimulationEnvironment.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/389)

[cw] Display metadata for similar cases

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/SimulationEnvironment.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/390)

[cw] Remove the fixed panel in top-right for Simulation

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-skin/src/main/resources/learnpad/less/learnpad.less

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/396)

[cw] Change background color for Jumbotron

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationPanel.xml
lp-platform/build
lp-platform/lp-platform-distributions/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/394)

[cw] Improve tests in recommendation panel

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationPanel.xml
lp-platform/build
lp-platform/lp-platform-distributions/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/398)

[cw] Create empty patches object

---

lp-platform/build
lp-platform/lp-platform-distributions/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/399)

[cw] Put a pre-configuration of the build for review

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/SimulationEnvironment.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/392)

[cw] Use the configurable REST Prefix for simulation

---

lp-platform/build

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/400)

[build] Fix some build problems for 'review' profile

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/SimulationEnvironment.xml
lp-core-platform/lp-cp-conf/src/main/java/eu/learnpad/configuration/LearnpadPropertiesConfigurationSource.java
lp-core-platform/lp-cp-conf/src/main/resources/learnpad.properties.vm
lp-platform/lp-platform-distributions/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/401)

[cw] Make CW's addresses configurable

---

lp-model-verification/lp-verification-component/src/main/java/eu/learnpad/verificationComponent/Server.java
lp-model-verification/verification-component-deadlock-plugin/src/main/java/eu/learnpad/verification/plugin/pn/modelcheckers/LOLA.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/402)

LOLA slow start fix

---

lp-platform/lp-platform-conf/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/407)

[cw] Add attachments tab at the bottom

---

lp-collaborative-workspace/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/408)

[cw] Documentation of interfaces

---

lp-model-environment/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/409)

[me] Documentation for Modelling Environment

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiController.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/Main.java

This PR should contribute to the issue #352
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/411)

Remove xwiki notion in user

---

lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/ca/XwikiBridgeInterfaceRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/ca/XwikiCoreFacadeRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiBridgeInterfaceRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiCoreFacadeRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/or/XwikiBridgeInterfaceRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/or/XwikiCoreFacadeRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/qm/XwikiBridgeInterfaceRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/qm/XwikiCoreFacadeRestResource.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/415)

Fixed Undesidered "PrintStackTrace" With Exception Chaining in CP

---

lp-simulation-environment/build
lp-simulation-environment/scripts/start
lp-simulation-environment/scripts/stop

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/422)

[sim] Fix the build to put everything in the 'out' folder

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/CWXwikiBridge.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/RecommendationWebsocketServer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/425)

[cw] Improve concurrent access to maps

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/UICWBridge.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/CWXwikiBridge.java
lp-collaborative-workspace/lp-cw-component/lp-cw-component-service/src/main/java/eu/learnpad/cw/service/script/LearnpadScriptService.java
lp-collaborative-workspace/lp-cw-component/lp-cw-component-skin/src/main/resources/learnpad/less/learnpad.less
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/Dashboard.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/ProfilePanel.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationPanel.xml
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/ScoreUpdateReceiver.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/data/ScoreRecord.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/data/ScoreRecordCollection.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiBridgeInterfaceRestResource.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/426)

[cw] Add a dashboard

---

lp-content-analysis/src/main/java/eu/learnpad/ca/impl/BridgeImpl.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/ColloborativeContentVerifications.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/StaticContentVerifications.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/QualityCriteria.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/ContentAnalysisProxy.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/ca/XwikiBridgeInterfaceRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiController.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiCoreFacadeRestResource.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/433)

Cw api integration with ca

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/CollaborativeDocumentSheet.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/434)

[cw] Add a link to results for CA analysis

---

lp-content-analysis/src/main/java/eu/learnpad/ca/impl/BridgeImpl.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/435)

fixed annotation

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/UICWBridge.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/CWXwikiBridge.java
lp-collaborative-workspace/lp-cw-component/lp-cw-component-service/src/main/java/eu/learnpad/cw/service/script/LearnpadScriptService.java
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/SimulationEnvironment.xml
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/Simulation.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiController.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiCoreFacadeRestResource.java

* Use the following link to join the simulation
http://localhost:8080/xwiki/bin/view/LPUI/SimulationEnvironment?simulationid=9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/437)

[cw] Add joinSimulation functionality

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/Simulator.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/EventDispatcherImpl.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/AbstractProcessDispatcher.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/robot/RobotUserEventReceiver.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/robot/RobotUserEventReceiverWrapper.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/robot/activiti/ActivitiRobotInputExtractor.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImpl.java

Robot functionnalities were not quite up to date with the latest platform developments.
The main change concerns the fact that the robots now use the simulator internal event functionality, instead of the previous weird wrapper around the user event receiver. This allows for a nicer, less bug-prone design.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/438)

[sim] Update Robots

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/UICWBridge.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/CWXwikiBridge.java
lp-collaborative-workspace/lp-cw-component/lp-cw-component-service/src/main/java/eu/learnpad/cw/service/script/LearnpadScriptService.java
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/ProfilePanel.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/SimulationEnvironment.xml
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/Simulation.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/data/ProcessInstanceData.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiController.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiCoreFacadeRestResource.java
lp-platform/lp-platform-conf/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/439)

[cw] Add the Join simulation button in the Profile panel

---

lp-content-analysis/build
lp-content-analysis/lp-ca-ui/build
lp-content-analysis/lp-ca-ui/pom.xml
lp-content-analysis/lp-ca-ui/scripts/start
lp-content-analysis/lp-ca-ui/scripts/stop
lp-content-analysis/scripts/start
lp-content-analysis/scripts/stop

java 8 dependencies removed
@gulyx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/444)

[ca] build bug fixed

---

lp-content-analysis/README.md
lp-content-analysis/lp-ca-ui/src/main/java/ContentAnalysisBean.java
lp-content-analysis/lp-ca-ui/src/main/webapp/getanalysis.xhtml

fix bug rendering CA UI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/445)

[ca] UI rendering improved

---

launch

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/449)

Applied the same changes in PR #448 to the launch script

---

lp-content-analysis/lp-ca-ui/src/main/webapp/getanalysis.xhtml

@gulyx issue #447 fixed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/456)

[ca] issue #447 fixed

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/ProfilePanel.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/457)

Hided ProfilePanel if Guest

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Browsing.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Browsing.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Comments.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Comments.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/ContentAnalysis.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/ContentAnalysis.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Contributions.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Contributions.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Feedback.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Feedback.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Patch.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Patch.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Recommandations.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Recommandations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Simulation.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Simulation.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/WebHome.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/ContentAnalysis.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/DocsPanel.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/WebHome.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/WebIDE/LearnPAd.xml
lp-platform/lp-platform-conf/pom.xml

@cjdelisle please help me to revise it. On my local it compiles and looks working, but I would l like that 
you check (and maybe accept) this PR. Let me know.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/450)

First proposal for the DocPages (in English)

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/pom.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/XWiki/Admin.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/465)

Added an Admin user in order that the superadmin user is not necessary

---

lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/me/XwikiController.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/leranpad/core/impl/others/MVStubber.java
lp-model-environment/README.md

Added STUBS supporting MD and LPZIP files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/470)

Cp first support for md

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/LinkClass.xml
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/leranpad/core/impl/others/MVStubber.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/471)

CW modified link class

---

lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/me/XwikiController.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/472)

Fixed wrong comparison between instances of an enumeration

---

lp-model-transformer/src/main/resources/transformation/ado2xwiki.atl

this PR correct the issue in the Generation Process (#359) point n.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/468)

Upgraded issue solver

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/LinkClass.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/WorkflowButtonsMacro.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/473)

Cw display denomination property

---

lp-dashboard-kpi/lp-dash-bridge/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/487)

Improved Documentation in the README

---

lp-platform/lp-platform-conf/pom.xml
lp-platform/lp-platform-distributions/lp-platform-jetty-hsqldb/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/492)

Enable English and Italian languages in the platform

---

lp-simulation-environment/simulator/src/main/resources/process/y3demo.bpmn20.xml

Forgot to add a license for the y3 demo process. This is now corrected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/496)

[sim] Add license file for y3 demo process

---

lp-simulation-environment/simulator/src/main/resources/validation_db.json

Add some more validation options for some tasks
Add validation for usertask16
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/501)

[sim] Y3 demo process - more validation

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Browsing.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Comments.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/ContentAnalysis.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Contributions.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Feedback.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Recommandations.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Simulation.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/WebHome.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/WelcomePage.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/WelcomePage.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/503)

Cw improve tours description

---

lp-dashboard-kpi/build
lp-dashboard-kpi/lp-dash-adoxx-cockpit/scripts/start
lp-dashboard-kpi/lp-dash-adoxx-cockpit/scripts/stop

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/504)

Dash modify service deployment

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/DocsPanel.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/510)

Cw add help desk support ui

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/CommentAnalysis.xml
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/CoreFacade.java
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/SemanticWiki.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiController.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiCoreFacadeRestResource.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/514)

Cw extendig api for comment analysis support

---

lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiCoreFacadeRestResource.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/or/XwikiBridgeInterfaceRestResource.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/516)

Solving issue 515

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/actuators/CollaborativeDocumentActuator.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/actuators/FeedbackActuator.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/actuators/ModelElementAbstractActuator.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/actuators/ModelElementAttachmentActuator.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/actuators/ModelElementCommentActuator.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/actuators/SimpleEventActuator.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/listeners/CollaborativeDocumentListener.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/listeners/FeedbackListener.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/listeners/ModelElementAttachmentListener.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/listeners/ModelElementCommentListener.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/listeners/SimpleEventListener.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/518)

Cw event listeners with threads

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/WelcomePage.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/BaseElementSheet.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/ModelSheet.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUsers/AddUsersScript.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUsers/UsersListY3Demo.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/519)

User creation script

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/api/impl/ResourceNotFoundExceptionMapper.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/robot/IRobotInputExtractor.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/robot/RobotUserEventReceiver.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/robot/activiti/ActivitiRobotInputExtractor.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/robot/activiti/markovrobot/MarkovBotFactory.java
lp-simulation-environment/simulator/src/main/resources/dataobjects/y3demo_DataObject_usertask01
lp-simulation-environment/simulator/src/main/resources/process/y3demo.bpmn20.xml
lp-simulation-environment/simulator/src/main/resources/static/TaskReceiver.js
lp-simulation-environment/simulator/src/main/resources/validation_db.json

This PR introduces several improvements and fixes related to the y3 demo process
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/522)

[sim] Y3 demo process improvements

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/activiti/scoreprobe/IProbeScoresReceiver.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/event/impl/SimulationEndSimEvent.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManager.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImpl.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIServlet.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/user/send/SessionFinished.java
lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImplTest.java

This serie of commits introduce some integration with the Monitoring score events.
Currently, no connection to the Mon is actually done, but this PR introduce the necessary changes to create the pipeline in order to propagate them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/526)

[sim] Start monitor probe integration

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManager.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImpl.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIServlet.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/utils/BPMNExplorer.java
lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImplTest.java

Some cleanup of generics type declaration.
No functional change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/532)

 [sim] Generics cleanup

---

lp-simulation-environment/monitoring/scripts_build/common

db folder copy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/536)

[mon] updated script for copying also data folder

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/api/impl/SimulatorBridgeImpl.java

Removed some more redundant generics.
No functional changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/535)

[sim] Some more generics cleanup

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/Main.java
lp-simulation-environment/simulator/src/main/resources/process/suap-y2r.bpmn20.xml
lp-simulation-environment/simulator/src/main/resources/process/y3demo.bpmn20.xml
lp-simulation-environment/simulator/src/main/resources/static/Process.js
lp-simulation-environment/simulator/src/main/resources/static/SingleProcess.js
lp-simulation-environment/simulator/src/main/resources/validation_db.json

The simulator now load both the titolo unico single-user process and the
service conference multiuser process.
Update the IDs of these two processes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/544)

[sim]  fixes IDs and add back titolo unico single-user process

---

lp-simulation-environment/monitoring/configFiles/environmentFile
lp-simulation-environment/monitoring/scripts/configFiles/environmentFile
lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/configFiles/environmentFile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/546)

Fixed IP address monitor part

---

lp-simulation-environment/deployment/marche/simulator.properties
lp-simulation-environment/deployment/marche/simulator.propertiesOLD

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/549)

Sim fix deply conf file

---

lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/UICWBridge.java
lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/CWXwikiBridge.java
lp-collaborative-workspace/lp-cw-component/lp-cw-component-service/src/main/java/eu/learnpad/cw/service/script/LearnpadScriptService.java
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/Dashboard.xml
lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/DashboardKPIProxy.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiController.java
lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiCoreFacadeRestResource.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/552)

Enact kpi calculation from CW UI

---

lp-collaborative-workspace/README.md
lp-model-environment/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/554)

Updated Documentation

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/Main.java
lp-simulation-environment/simulator/src/main/resources/process/suap-it.bpmn20.xml

The simulator now loads the italian version of the SUAP process instead
of the english one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/557)

[sim] Replace SUAP with italian version 

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/Main.java
lp-simulation-environment/simulator/src/main/resources/process/serviceconference-it.bpmn20.xml

The simulator now loads the italian version of the Service Conf process
instead of the english one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/558)

[sim] Replace Service Conf with italian version

---

lp-collaborative-workspace/README.md
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUsers/UsersListY3Demo.xml
lp-model-environment/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/560)

Remove duplicated user

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/SimulationAnswers.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/SimulationEnvironment.xml
lp-platform/lp-platform-distributions/lp-platform-jetty-hsqldb/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/562)

Ui simulation help

---

lp-dashboard-kpi/README.md
lp-ontology-recommender/README.md
lp-ontology-recommender/pom.xml
lp-ontology-recommender/src/main/java/eu/learnpad/ontology/kpi/data/ExcelParser.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/568)

Or fix logging problem importing excel

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/Dashboard.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationPanel.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/569)

Cw rec panel added check on guest

---

lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Simulation.it.xml
lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/Simulation.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/570)

Improved Docs.

---

lp-simulation-environment/deployment/marcheSimpleRobots/simulator.properties
lp-simulation-environment/deployment/simpleRobots/simulator.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/576)

Sim further deployment files

---

lp-ontology-recommender/README.md
lp-ontology-recommender/src/main/java/eu/learnpad/ontology/simulation/SimulationScoreLog.java
lp-ontology-recommender/src/main/java/eu/learnpad/or/impl/OntologyRecommenderImpl.java
lp-ontology-recommender/src/test/java/eu/learnpad/ontology/kpi/dashboard/AbstractKpiTest.java
lp-ontology-recommender/src/test/java/eu/learnpad/ontology/kpi/dashboard/KPILoaderTest.java
lp-ontology-recommender/src/test/java/eu/learnpad/ontology/kpi/dashboard/KpiAssessmentTest.java
lp-ontology-recommender/src/test/java/eu/learnpad/ontology/simulation/SimulationScoreLogTest.java
lp-ontology-recommender/src/test/java/eu/learnpad/or/impl/OntologyRecommenderImplTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/564)

handle simulation score map in OR log

---

lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/activiti/scoreprobe/IProbeScoresReceiver.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/activiti/scoreprobe/ScoreProbeConsumer.java
lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManager.java
lp-simulation-environment/simulator/src/main/resources/static/TaskReceiver.js

This PR fixes some bugs causing the probe scores not to be correctly registered and improve the display of probe scores on the UI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/586)

[sim] Improve MON probe integration

---

lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/impl/PathExplorerImpl.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/592)

[mon] updating score values

---

lp-collaborative-workspace/pom.xml
lp-content-analysis/lp-ca-ui/pom.xml
lp-content-analysis/pom.xml
lp-core-platform/pom.xml
lp-dashboard-kpi/lp-dash-adoxx-cockpit/pom.xml
lp-dashboard-kpi/lp-dash-bridge/pom.xml
lp-dashboard-kpi/pom.xml
lp-model-transformer/pom.xml
lp-model-verification/lp-verification-component/pom.xml
lp-model-verification/verification-component-deadlock-plugin/pom.xml
lp-model-verification/verification-component-understandability-plugin/pom.xml
lp-model-verification/verification-component/pom.xml
lp-simulation-environment/monitoring/pom.xml
lp-simulation-environment/simulator/pom.xml

for all the dependency of the maven-compiler-plugin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/593)

Forced the UTF-8 ecncoding

---

lp-model-transformer/README.md

the responsible is Alfonso Pierantonio and Gianni and Francesco the collaborators
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/596)

update responsible field

---

lp-simulation-environment/simulator/src/main/resources/static/TaskReceiver.js

Change the scores desc in UI according to proposal in #577 
Minor fixes

[sim] Update score desc in ui

---

lp-ontology-recommender/src/main/java/eu/learnpad/ontology/simulation/SimulationScoreLog.java
lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/impl/LearnerAssessmentManagerImpl.java
lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/storage/H2Controller.java
lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/storage/MySqlController.java
lp-simulation-environment/simulator/src/main/resources/static/TaskReceiver.js

from sim point of view I just updated label of the scores shown at the end of the simulation.
from mon point of view I updated some scores calculation in order to keep it clearer according with the updates done to the label.
@gulyx @tomjorquera 
in attachment an example of the displayed scores.

[sim-mon] updates for scores UI and scores calculation
