LearnPAd/learnpad

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/Bridge.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/BridgeInterface.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/Controller.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/CoreFacade.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/ColloborativeContentVerifications.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/StaticContentVerifications.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/Annotation.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/Content.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/Node.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/QualityCriteria.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/collaborative/AnnotateCollaborativeContentAnalysis.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/collaborative/CollaborativeContent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/collaborative/CollaborativeContentAnalysis.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/stat/AnnotateStaticContentAnalysis.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/stat/StaticContent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/ca/rest/data/stat/StaticContentAnalysis.java
Bridge and Core interfaces added for the Content Analysis component, with REST API description and associated data format.  The ca.rest.data package contains the description of the different data structures required for creating Static or Collaborative Content. The classes contained in this package are annotated with JAXB for marshalling and  unmarshalling XML file.  other information are present in  wiki page: http://wiki.learnpad.eu/LearnPAdWiki/bin/view/Component/Content+Analysis
> REST API for the Content Analysis component Added

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/BridgeInterface.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/CoreFacade.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/IProcessHandlingAPI.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/ISimulationMonitoringAPI.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/IUserInfosAPI.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/data/ProcessData.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/data/ProcessInstanceData.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/data/UserData.java
NOTE: this PR is the updated version of PR #38
Add Bridge and Core interfaces for the simulator, with REST API
description and associated data format.
The sim.rest.data package contains the description of the different data
structures required for creating and instantiating processes, as well as
for describing users.
The classes contained in this package are meant to be converted in and
from JSON when being passed to or by the REST API.
Notably, the sim.rest.IUserInfosAPI interface and sim.rest.data.UserData
class describe the expected API provided by the core facade. It seems a
little weird to describe them here since several modules may require the
same functionalities, each declaring similar interfaces...
Maybe these parts of the spec could be reified to a common shared
package.
> Add REST API for the simulator component

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/exception/impl/LpRestExceptionXWikiImpl.java
Made the class eu.learnpad.exception.impl.LpRestExceptionXWikiImpl.java
more robust by promoting it to Final, and changing the name of its
static method to a more proper one.
> Small fix on the exceptions

- lp-simulation-environment/build
- lp-simulation-environment/pom.xml
- lp-simulation-environment/scripts/start
- lp-simulation-environment/scripts/stop
- lp-simulation-environment/src/main/resources/assembly.xml
The previous system to generate uber jar had several limitations, which
threatened to cause problems (and actually started to do so in the REST
branch).
The initial plan was to replace assembly with the shade plugin, but we
reached a limit in the number of files which can be contained into a jar
file(!).
The current solution is described here:
http://stackoverflow.com/questions/13021423/invalid-or-corrupt-jar-file-built-by-maven-shade-plugin
and here:
https://ath3nd.wordpress.com/2013/12/25/packaging-a-multimodule-maven-spring-app-in-a-standalone-jar/
> [sim] Overhaul of the build system

- lp-simulation-environment/pom.xml
- lp-simulation-environment/src/main/java/eu/learnpad/simulator/Simulator.java
- lp-simulation-environment/src/main/java/eu/learnpad/simulator/api/impl/ResourceNotFoundExceptionMapper.java
- lp-simulation-environment/src/main/java/eu/learnpad/simulator/api/impl/SimulatorBridgeApplication.java
- lp-simulation-environment/src/main/java/eu/learnpad/simulator/api/impl/SimulatorBridgeImpl.java
- lp-simulation-environment/src/main/java/eu/learnpad/simulator/api/impl/SimulatorBridgeServletHolder.java
- lp-simulation-environment/src/main/java/eu/learnpad/simulator/uihandler/webserver/WebServer.java
- lp-simulation-environment/src/test/java/eu/learnpad/simulator/uihandler/webserver/WebServerTest.java
The simulator module now implements and exposes the rest API defined in [lp-cp-apis](https://github.com/LearnPAd/learnpad/tree/d202cae6ceda0482b42c1bb2edd08a46b3360c9b/lp-core-platform/lp-cp-apis)
> [sim] Add Simulator REST API impl

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/IProcessHandlingAPI.java
It seems that some of the lastest modifications to the REST API have been a little hasty. As it turns out, making a REST API via JAX-RS is not as simple as defining a Java interface.
This should not really create a problem (and require no actual change in the implementation since it only modify some annotations). But I still created a PR to make you aware of the change, since it concerns the API.
Also, maybe it will allow you to avoid those easy mistakes I made.
Here are the actual changes:
The following shortcomings have been corrected:
- No longer use the same path for several POST requests (`/instances`).
REST API do not support "method overloading", making one of the two
methods being shadowed by the other and causing HTTP errors as the
parameters would not correspond.
Note: using the …
> Minor corrections to Sim REST API

- build-system/postbuild.sh
Improve the build tool: when no `start` exists, don't run it.
> [build] Do not use 'start' if not needed

- lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-transformer/resources/model/TitoloUnico.xmi
- lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-transformer/resources/model/TitoloUnico.xml
I'm trying to add Titolo Unico into the process but I'll need your help @Bitico.  I first added the Adoxx file as an XML.  Then, I saw that some transformations was needed in order to make it XMI (add namespaces, change uppercase to lowercase for first letter of element).  You can find both files (XML and XMI) in the current Pull Request.  Then I tried to run `eu.learnpad.transformations.run.MainTest` to do the transformation (I changed the model file for the input).  This is the result.
```
The input file exist!
[Fatal Error] :1:57: Le type d'élément "Ado:ADOXMLTypexmi" doit être suivi des spécifications d'attribut, ">" ou "/>".
Exception in thread "main" org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 57; Le type d'élément "Ado:ADOXMLTypexmi" doit être suivi des …
```
> Add Titolo Unico process in the transformer

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/data/ProcessInstanceData.java
- lp-simulation-environment/src/main/java/eu/learnpad/simulator/IProcessManager.java
- lp-simulation-environment/src/main/java/eu/learnpad/simulator/api/impl/SimulatorBridgeImpl.java
- lp-simulation-environment/src/main/java/eu/learnpad/simulator/monitoring/activiti/ActivitiProbe.java
- lp-simulation-environment/src/main/java/eu/learnpad/simulator/processmanager/AbstractProcessDispatcher.java
- lp-simulation-environment/src/main/java/eu/learnpad/simulator/processmanager/IProcessDispatcher.java
- lp-simulation-environment/src/main/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManager.java
- lp-simulation-environment/src/main/java/eu/learnpad/simulator/processmanager/activiti/processdispatcher/ActivitiProcessDispatcher.java
- lp-simulation-environment/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/process/send/ProcessData.java
- lp-simulation-environment/src/test/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManagerTest.java
- lp-simulation-environment/src/test/java/eu/learnpad/simulator/processmanager/activiti/processdispatcher/ActivitiProcessDispatcherTest.java
Previous version of the simulator made references to internal process definition ID differing from the ones defined in the BPMN files.
This made interactions with the Simulator more complicated and error-prone.
This PR modify the simulator to use the process definition IDs defined in the BPMN files in its external APIs (along with various minors fixes).
> Improve interaction with the Simulator

- lp-core-platform/build
- lp-core-platform/scripts/start
- lp-core-platform/scripts/stop
These scripts are not need in `lp-core-platform` which is only a dependency of `lp-platform`.
> [cp] Remove scripts start/stop

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/core/impl/or/XwikiBridgeInterfaceRestResource.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/core/impl/or/XwikiController.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/core/impl/or/XwikiCoreFacadeRestResource.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/CoreFacade.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/GetComments.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/ModelImporter.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/ModelSetImported.java
- lp-ontology-recommender/src/main/java/eu/learnpad/or/impl/OntologyRecommenderImpl.java
the import operation of a model set have been aligned
with the import operation foreseen by the CW. Specifically,
the CP notifies the OR that a new model is available, then the
OR retreives the model on the CP by means of the CoreFacade.
> modified API for OR component.

- lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiCoreFacadeRestResource.java
This is a proposal to remove the direct connection between the CW CoreFacadeRestResurce
and the Simulator.
In fact as discussed already in PR #111, the CoreFacadeRestResource implements HTTP
requests to the remote REST resources on the corresponding Core Facade on the LCP.
> Fix the CW CoreFacadeRestResurce on Simulator

- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/utils/BPMNExplorer.java
Java 7 has a bug regarding nio package and archive files (see
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7156873).
To avoid this bug, replace nio use with more "traditional" file opening
method.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/163)
> [sim] Java 7 nio file path bug workaround

- lp-simulation-environment/simulator/src/main/resources/static/Task-jsonform.js
The form handler now saves the submitted values (in a session storage)
and restores them if the user has to resubmit the form (when previous
submission was incorrect).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/171)
> [sim] save and restore submitted form values

- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/TaskServlet.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImpl.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIServlet.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/task/send/Resubmit.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/task/send/TaskDesc.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/user/send/SessionFinished.java
- lp-simulation-environment/simulator/src/main/resources/static/Task.js
- lp-simulation-environment/simulator/src/main/resources/static/TaskReceiver.js
- lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImplTest.java
This PR introduces a series of changes aiming at making the simulator web ui more session oriented.
Previous version would work on a "process" basis, sorting tasks by processes and sending notifications on process end. This was not very consistent with the principle of sessions.
This version changes the UI logic to work on a "session" basis instead. Meaning that a user will receive tasks from the same session at the same place (even if they belong to different processes), and will be notified of completion when the session end.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/193)
> [sim] Change Sim web UI to be more session-oriented

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/IUserInfosAPI.java
The path annotations on the IUserInfosAPI interface were incorrect. A
base path was set at the interface level, and relative path at the
methods level. This does not works as the interface is implemented by a
class with its own base path.
The annotations are now corrected to be at the methods level only.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/199)
> Correct Sim user infos API path annotations

- lp-simulation-environment/simulator/src/main/resources/ui.html
Previous versions of the web ui would convert the passed username to
lower case for demo purpose (being able to type 'Barnaby' for the id
'barnaby').
Now that we have a cleaner handling of users, this causes bugs when the
user id is not in lower case.
Fixing this by removing lower case conversion.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/201)
> [sim] Correct bug in Web UI user id parsing

- lp-simulation-environment/simulator/src/main/resources/static/Task.js
- lp-simulation-environment/simulator/src/main/resources/static/Users.js
The user data handling part of the WebUI contained a mistake that could
cause it to try to violate a CORS restriction. This bug would not appear
when tested on the localhost.
This commit fixes the bug by setting the destination address explicitely.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/202)
> [sim] Correct CORS mistake in Sim WebUI client

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/qm/rest/NotificationsFromBridge.java
- lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/qm/XwikiController.java
- lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/qm/XwikiCoreFacadeRestResource.java
- lp-questionnaire-manager/src/test/java/eu/learnpad/qm/tests/learnpad/XwikiCoreFacadeRestResourceTest.java
Probably this change will impact on the PR#192 :
see https://github.com/LearnPAd/learnpad/pull/192/files#diff-75edf02b4f75a1c8e20e9a1c2565b92eR165
Thus a simple fix is requred also there.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/219)
> Fixed a typo in the API, and all the related classes.

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/IEventReceiver.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/IProcessHandlingAPI.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/ISimulationMonitoringAPI.java
- lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/api/rest/corefacade/SimRestAPICoreFacadeTest.java
sim REST API methods now declare that they can throw a LpRestException.
This will allow for a better and more consistent handling of error
during calls to these methods.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/235)
> [sim] Update sim API to declare LpRestException

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/IProcessHandlingAPI.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/AbstractEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/ProcessEndEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/ProcessStartEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/SessionScoreUpdateEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/SimulationEndEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/SimulationStartEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/TaskEndEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/TaskFailedEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/TaskStartEvent.java
- lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/mv/XwikiController.java
- lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/sim/XwikiBridgeInterfaceRestResource.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/IProcessManager.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/api/impl/SimulatorBridgeImpl.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManager.java
- lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/api/rest/corefacade/SimRestAPICoreFacadeTest.java
This serie of commits update the Sim REST API and implementation to store and send back optional modelsetid associated with processes.
Note that it does not (yet) update the monitoring part in charge of sending events associated with the new API, nor the required modelsetid passing from the simulator to the monitoring.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/241)
> Update Sim API and impl to store modelsetid information

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/AbstractEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/ProcessEndEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/ProcessStartEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/SessionScoreUpdateEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/SimulationEndEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/SimulationStartEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/TaskEndEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/TaskFailedEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/TaskStartEvent.java
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/manager/RestNotifier.java
- lp-simulation-environment/monitoring/src/test/java/eu/learnpad/simulator/mon/TestSimulatorMonCoreFacadeRESTResource.java
- lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/api/rest/corefacade/SimRestAPICoreFacadeTest.java
The sim events defined in the API now all include the data associated
with the simulation session.
Updated implementation and tests accordingly.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/251)
> Add simulation session data to all Sim API events

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/AbstractEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/EventType.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/ProcessEndEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/ProcessStartEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/SessionScoreUpdateEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/SimulationEndEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/SimulationStartEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/TaskEndEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/TaskFailedEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/TaskStartEvent.java
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/event/GlimpseBaseEventBPMN.java
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/impl/ComplexEventProcessorImpl.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/IProcessManager.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/Simulator.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/activiti/ProbeEventReceiver.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/event/impl/SessionScoreUpdateSimEvent.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/event/impl/TaskEndSimEvent.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/AbstractProcessDispatcher.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManager.java
- lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImplTest.java
This PR introduces a serie of commits whose ultimate goal is to change the probe format for communication between the simulator and the monitoring submodules.
In this new format, instead of the probe events containing a list of fields, they simply contain an event object, based on the events defined in the Sim REST API.
This change ensures that the sim always pass to the mon all the required infos regarding the content of the events.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/261)
> [sim][mon] Update probe event format

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/AbstractEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/ProcessEndEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/ProcessStartEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/SessionScoreUpdateEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/SimulationEndEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/SimulationStartEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/TaskEndEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/TaskFailedEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/TaskStartEvent.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/IProcessManager.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManager.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImpl.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIServlet.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/user/send/SessionFinished.java
- lp-simulation-environment/simulator/src/main/resources/static/TaskReceiver.js
- lp-simulation-environment/simulator/src/main/resources/ui.html
The events defined in the Sim Rest API now implement serializable. This
allows for modules to manipulate and pass them among each others.
This is notably required for the Glimpse probes used in the mon
submodule.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/267)
> Made Sim Rest API events serializable

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/me/rest/ImportModelSet.java
- lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/me/XwikiController.java
- lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/me/XwikiCoreFacadeRestResource.java
Considering step 20. and 24. from [Slice A](http://wiki.learnpad.eu/LearnPAdWiki/bin/view/WP10/Slice+A) of the scenario, the simplest is to return the Verification Process ID to ME when pushing a new model.  After that, he can get the verification results trough the existing API with this ID.
@gulyx, does it seems OK to you?
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/268)
> [me] Return Verification Process ID when pushModel

- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/activiti/ProbeEventReceiver.java
- lp-simulation-environment/simulator/src/main/resources/glimpse_server.conf
Replace the old remote glimpse server with a configuration file that
specifies the address to use. By default this file contains the address
of the local glimpse server created by the monitoring component.
Fixes PR #303
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/309)
> [sim] Use local glimpse server

- lp-simulation-environment/monitoring/pom.xml
- lp-simulation-environment/monitoring/scripts_build/common
Some information in the build script and configuration were outdated,
causing the component to fail build. This has now been fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/310)
> [mon] Update build script and config

- lp-simulation-environment/README.md
- lp-simulation-environment/simulator/README.md
- lp-simulation-environment/simulator/pom.xml
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/activiti/ProbeEventReceiver.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/WebServer.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/utils/SimulatorProperties.java
- lp-simulation-environment/simulator/src/main/resources/glimpse_server.conf
- lp-simulation-environment/simulator/src/main/resources/simulator.properties
This PR introduces additional mechanisms to support an optional properties file.
This properties file allows to override some default properties values:
- the IP used by the simulator
- the address of the glimpse server
This properties file must named `simulator.properties` and placed in the folder from which the simulator is started (typically the ./out subfolder if launching the simulator with the start script).
To override the address user by the simulator, put the following inside the file:
`address=<address>`
To override the glimpse server, put the following inside the file:
`glimpse_server=tcp://<address>`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/318)
> [sim] Add properties file handling

- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/datastructures/document/LearnPadDocument.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/datastructures/document/LearnPadDocumentField.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/processdispatcher/ActivitiProcessDispatcher.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/formhandler/AbstractFormHandler.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/formhandler/activiti2jsonform/ActivitiToJsonFormFormHandler.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/formhandler/dataobject2jsonform/DataObjectToJsonFormFormHandler.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/formhandler/multi2jsonform/Multi2JsonFormFormHandler.java
The current design of input data objects was incorrect and did not
really work. This commit introduces a rewrite that change the way
document fields are handled and unify it with the FormHandler FormFields
(which are consequently removed).
This mean that the fields are parsed in an uniform way, but cause a lot
of small type rewrites.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/326)
> [sim] Rework of input data objects

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/ProcessEndEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/ProcessStartEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/SessionScoreUpdateEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/TaskEndEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/TaskFailedEvent.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/TaskStartEvent.java
- lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/sim/XwikiController.java
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/manager/RestNotifier.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/IProcessEventReceiver.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/EventDispatcherImpl.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/activiti/ProbeEventReceiver.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/event/impl/SessionScoreUpdateSimEvent.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/event/impl/TaskFailedSimEvent.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/AbstractProcessDispatcher.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/robot/RobotUserEventReceiverWrapper.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImpl.java
- lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/api/rest/corefacade/SimRestAPICoreFacadeTest.java
The REST messages contained reference to simulator-specific ID for tasks
and processes. This implied that the other component had to use the sim
REST API to translate these simulator-specific IDs into known ones.
This commit replaces all simulator specific events IDs with shared ones,
and modifies the various implementations accordingly.
This PR also include a bunch of internal simulator improvements/fixes regarding events.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/327)
> Rework of the Sim REST Event API

- lp-simulation-environment/simulator/src/main/resources/static/TaskReceiver.js
The Sim Web Ui now shows the total score under the tasks scores in the
summary table at the end of a simulation session.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/330)
> [sim] SimWebUI shows total score on session end

- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/IProcessManager.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/activiti/ProbeEventReceiver.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManager.java
A bug caused the modelsetid to be missing in events sent to the monitoring subcomponent. This PR fixes the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/338)
> [sim] Fix missing modelsetid in events

- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/activiti/ProbeEventReceiver.java
When passing sim session data to the glimpse probe, clean some useless
stuff added by the simulator for internal management.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/376)
> [sim] Clean sim session data passed to glimpse

- lp-simulation-environment/simulator/src/main/resources/dataobjects/SCIA_DataObject1
Remove TODO line from one of the Y2 demo data objects. Sadly this was
not fixed in time for the demo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/385)
> [sim] remove TODO from y2demo data object

- lp-simulation-environment/simulator/src/main/resources/static/Task-jsonform.js
WebUI now checks if it has access to sessionStorage functionalitites
before trying to use them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/406)
> [sim] Check sessionStorage errors in WebUI

- lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/Simulation.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/data/UserDataCollection.java
- lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiController.java
- lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiCoreFacadeRestResource.java
The type Collection<UserData> was incorrectly unmarshalled by the
platform. This fix introduces the UserDataCollection class that ensure
the correct (un)marshalling by encapsulating the collection into a
container object.
Fixes issue #352
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/413)
> [cw] Correct UserData coll. unmarshalling

- lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/CWXwikiBridge.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/BridgeInterface.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/ScoreUpdateReceiver.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/data/ScoreRecord.java
- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/cw/rest/data/ScoreRecordCollection.java
- lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiBridgeInterfaceRestResource.java
- lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/sim/XwikiController.java
This PR introduces a new API for the CW that allows to store and fetch session score items.
The goal of the API is to allows the CW web interface to fetch information about the scores obtained by the users during simulations sessions, in order to be able to display them into, e.g., a score leaderboard.
This API optionally allows to fetch scores by user, by process or both.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/424)
> [cw] Introduce CW API to store and fetch session score items

- lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPUI/RecommendationPanel.xml
- lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiController.java
Modified CW RecsPanel and the CP in CW Controller in order 
to properly deal with userids. In fact, the CP should be the only responsible to 
convert (if needed) the IDs among the components (in this case CW and OR).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/427)
> Cw cp fix user id for recommendations

- lp-simulation-environment/monitoring/scripts_build/build
- lp-simulation-environment/monitoring/scripts_build/install
- lp-simulation-environment/monitoring/scripts_build/test
- lp-simulation-environment/simulator/scripts_build/build
- lp-simulation-environment/simulator/scripts_build/install
- lp-simulation-environment/simulator/scripts_build/test
Sim build scripts contained a weird variation of a one-liner to get
current script directory. This may have been the result of a shortcut
gone wrong...
This worked on recent platforms due to the fact that, when BASH_SOURCE
contains only one element, BASH_SOURCE[-1] == BASH_SOURCE[0]. But it
caused failures on systems with older bash where -1 is not a valid
index (looking at you macos).
This commit fixes this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/432)
> [sim] fix weird index in build scripts

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/data/ProcessInstanceData.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/api/impl/SimulatorBridgeImpl.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/activiti/ProbeEventReceiver.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/AbstractProcessDispatcher.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManager.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/processdispatcher/ActivitiProcessDispatcher.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/robot/RobotUserEventReceiver.java
- lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/processmanager/activiti/processdispatcher/ActivitiProcessDispatcherTest.java
The visibility of the attributes in the ProcessInstanceData class has
been changed to private due to a requirement of velocity. However this
API change caused some breakage in the simulator implementation.
This commit completes the API modification and fixes the implementation.
See discussion on issue #440 for more info.
Fixes issue #440
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/458)
> Correct SIM API data attributes use and implem.

- lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPCode/Translations.xml
- lp-collaborative-workspace/lp-cw-component/lp-cw-component-ui/src/main/resources/LPDocs/WebHome.xml
this fixes the header of the livetable and enable the right translation as reported by issue #451
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/466)
> Cw fix docs live table headers

- lp-model-transformer/src/main/resources/transformation/ado2xwiki.atl
Issues in the Generation Process (#359) correction about: "missing or "wrongly" reported in the "crossing model" section"
This PR corrects points 3,4 and 5 of the email May 4, 2016 at 11:12 AM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/475)
> Correction of the issues in the Generation Process (#359)

- lp-simulation-environment/build
Sim build script contained mistakes causing it not to return an error on
failure. This caused the global script process to continue even when it
should have stopped due to error.
This commit fixes the script to return a correct error value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/498)
> [sim] fix build script to do global stop on errors

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/or/rest/data/Entity.java
- lp-ontology-recommender/src/main/java/eu/learnpad/or/impl/OntologyRecommenderImpl.java
the class in serialized with JAXB.
This commit should mitigate the bug discussed in ISSUE #520
Also there was a typo in the old version of the class.
This commit fixes that typo and propagate the change in the classes
using the renamed operations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/521)
> Defined the order of the elements in Entity when

- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/consumer/GlimpseAbstractConsumer.java
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/consumer/GlimpseConsumer.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/activiti/scoreprobe/ScoreProbeConsumer.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManager.java
This PR adds integration between sim and mon for score and bpmn probes.
From now, when a new session is created on the sim, it is associated with a score probe that both send the bpmn file  to the mon and receive scores events from the mon regarding the session.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/530)
> [sim][mon] Add integration for score probe

- lp-core-platform/lp-cp-apis/src/main/java/eu/learnpad/sim/rest/event/impl/ScoreUpdateEvent.java
- lp-simulation-environment/monitoring/configFiles/startupRule.drl
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/configFiles/startupRule.drl
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/coverage/Activity.java
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/impl/LearnerAssessmentManagerImpl.java
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/impl/PathExplorerImpl.java
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/impl/RulesPerPathGeneratorImpl.java
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/impl/startupRuleBackup.drl
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/manager/GlimpseManager.java
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/manager/LearnerAssessmentManager.java
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/manager/ResponseDispatcher.java
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/rules/RuleElements.java
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/rules/ScoreTemporaryStorage.java
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/storage/DBController.java
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/storage/H2Controller.java
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/storage/MySqlController.java
- lp-simulation-environment/monitoring/src/main/java/eu/learnpad/simulator/mon/storage/ScoreTemporaryStorage.java
Rules generation fixed according new parameters there are now a generation of rules related to the path completion and one related to the capture of all the sessionscoreupdate.
All the updated session score are stored and used at the end of
simulation (SIMULATION_END) for calculation of kpi and others value that
will be sent to the cp and to the sim.
Activity has been updated taking in account the parameter taskartifactid
that sill be used for matching the events instead of the taskName
parameter.
The updates on the ScoreUpdateEvent should be approved by @tomjorquera
and @semmeneg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/533)
> [mon] Updated rules generation and ScoreUpdateEvent

- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImpl.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIServlet.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/user/send/AddTask.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/user/send/DeleteTask.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/msg/user/send/ProcessFinished.java
- lp-simulation-environment/simulator/src/main/resources/static/TaskReceiver.js
- lp-simulation-environment/simulator/src/main/resources/ui.html
- lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImplTest.java
The user UI now supports an optional "sessionid" parameter.
If this parameter is specified, the UI will only show tasks and events
related to the given session.
This is used in the CW to display only the current simulation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/538)
> [sim] UI now support single session display

- lp-simulation-environment/simulator/README.md
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/WebServer.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/utils/SimulatorProperties.java
- lp-simulation-environment/simulator/src/main/resources/simulator.properties
- lp-simulation-environment/simulator/src/main/resources/static/TaskReceiver.js
- lp-simulation-environment/simulator/src/main/resources/ui.html
- lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/uihandler/webserver/WebServerTest.java
This PR adds an infobox at the top of a session displaying a link to join the session.
In order to add this feature, the PR introduces a new property in the simulator for setting the address of the platform.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/539)
> [sim] add infobox for multi-users sim url

- lp-simulation-environment/README.md
- lp-simulation-environment/build
Add the option to specify a "--name" argument in the ./build script,
where "name" correspond to subfolder in the `deployment` folder,
containing a set of files to be used for a specific deployment.
For example, if `deployment` contains a `test` folder, the command
./build --test will setup the files in this folder accordingly.
Update README accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/540)
> [sim] Add build option for specific deployments

- lp-simulation-environment/build
Previous version of the build script did not put files in the correct
place in case of deployment (damn you eclipse and your convenient load
paths).
This commit changes the build script to use the correct path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/543)
> [sim] fix deployment file path

- lp-simulation-environment/build
Still wasn't the correct path (forgot that the build copy files in
another directory, so a manual launch was not the correct way to test).
This one should *definitely* fix up the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/545)
> [sim] Fix deployment build (again)

- lp-simulation-environment/simulator/src/main/resources/ui.html
Add missing parameter to taskReceiver. This fixes the `undefined`
erroneous URL when displaying "join session" message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/547)
> [sim] Fix undefined CW url in join message

- lp-simulation-environment/build
Some conditions could cause the build script to fail with a "file
exists" error.
Change build script to avoid failing if folder is already created.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/550)
> [sim] fix build script "file exist" error

- lp-simulation-environment/simulator/src/main/resources/static/TaskReceiver.js
Fix an incorrect parameter in the "join session" message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/551)
> [sim] fix URL in "join session" message

- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/Main.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/formhandler/AbstractFormHandler.java
While the option was available on the GUI, the simulator did not
actually load robots until now. This would cause a simulation session
involving robots to hang indefinitely.
With this change, the robot option is actually in effect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/556)
> [sim] load robot

- lp-simulation-environment/simulator/src/main/resources/static/TaskReceiver.js
Add a message signaling that the user has no active task. The message
disappears when the user has active tasks, or when the session is
finished.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/559)
> [sim] Add "no active task" msg

- lp-simulation-environment/simulator/src/main/resources/static/Process.js
Add some missing default values for serviceconf initialization. These
parameters are needed in case one of the two other offices represent a
third-party *not* involved in the process, since in this case a robot
will not provide meaningful value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/572)
> [sim] fix serviceconf default params init

- lp-simulation-environment/simulator/pom.xml
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/Simulator.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/robot/activiti/markovrobot/onelevel/ObservationData.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/robot/activiti/markovrobot/onelevel/OneLevelMarkovBot.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/robot/activiti/markovrobot/onelevel/OneLevelMarkovBotFactory.java
- lp-simulation-environment/simulator/src/main/resources/markov/train.json
Simulation now uses MarkovBot instead of SimpleRobot.
MarkovBot is trained with the basic example training file provided.
These bots use a simple markov chain of
depth 1 to produce their output.
These bots are trained using a file format similar to the one of the
validation db. These training files contain a one-level context of each
observed answers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/573)
> [sim] Replace simple robots with markovbots

- lp-simulation-environment/simulator/README.md
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/Main.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/Simulator.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/formhandler/AbstractFormHandler.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/utils/SimulatorProperties.java
- lp-simulation-environment/simulator/src/main/resources/simulator.properties
Add support for a new `robot_type` property. This property can take the
following values:
- none (for no robot)
- simple (for simple robot)
- markov (for markov chain based robots)
The simulator uses the `robot_type` property to decide which type of
robots to instantiate in the platform (if any).
Add related doc in the README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/574)
> [sim] Simulator now have a `robot_type` property

- lp-simulation-environment/simulator/src/main/resources/static/SingleProcess.js
A previous update to the initialization of processes was not ported to
SingleProcess.js, this caused failures when using robots in the
integrated version of the UI.
This commit adds the missing initialization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/575)
> [sim] Fix servconf process init with robots

- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManager.java
MON needs to receive the BPMN *before* receiving the start event.
Change the order in which these two events are propagated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/581)
> [sim] Change notification order on processStart

- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/IProcessEventReceiver.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/EventDispatcherImpl.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/activiti/ProbeEventReceiver.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/activiti/scoreprobe/ScoreProbeConsumer.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/event/impl/SimulationEndSimEvent.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/event/impl/SimulationFinalizeSimEvent.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManager.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/robot/RobotUserEventReceiver.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImpl.java
- lp-simulation-environment/simulator/src/main/resources/static/TaskReceiver.js
- lp-simulation-environment/simulator/src/test/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImplTest.java
Probe score events were not correctly handed. They were not received
correctly, and when received were handled too late to be displayed.
Correct score probe step.
Introduce a new simulation event to separate the completion and the
finalization of a session. A session is completed when the process is
finished. A session is finalized when it is completed and a last probe
score event has been finalized (if the session is associated with a
probe). 	
The Web UI now display the probe scores at the end of a session if they
have been provided.
If not, it still falls back on the manually calculated session score.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/584)
> [sim] Fix probe score events handling and display probe scores if provided

- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/activiti/scoreprobe/ScoreProbeConsumer.java
- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManager.java
Score events did not work correctly for multiple users, waiting only for
the first message instead of all the users scores.
Now Manager checks that the scores for *all* users have been received
before finalizing the simulation session.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/learnpad/learnpad/591)
> [sim] Fix multi-user score events 

- lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/activiti/scoreprobe/ScoreProbeConsumer.java
Probes now only try to handle messages corresponding to their simulation
session.
> [sim] Filter probe events by sim session id

- lp-collaborative-workspace/build
- lp-content-analysis/build
- lp-content-analysis/lp-ca-ui/build
- lp-core-platform/build
- lp-dashboard-kpi/build
- lp-dashboard-kpi/lp-dash-adoxx-cockpit/build
- lp-learning-session-manager/build
- lp-model-transformer/build
- lp-model-verification/build
- lp-ontology-recommender/build
- lp-platform/build
- lp-questionnaire-manager/build
- lp-simulation-environment/build
- template-component/build
Enabled the "-Dhttps.protocols=TLSv1.2" option in the __MVN_PROFILE__ of the build scripts.
Specifically this is due to this issue:
* https://stackoverflow.com/questions/50824789/why-am-i-getting-received-fatal-alert-protocol-version-or-peer-not-authentic
> Enabled the "-Dhttps.protocols=TLSv1.2" option in the __MVN_PROFILE__
